/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard.index'
import { Route as AuthedCampaignsIndexRouteImport } from './routes/_authed/campaigns.index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedCampaignsCodeApplyRouteImport } from './routes/_authed/campaigns.$code.apply'
import { Route as AuthedDashboardProjectsCodeIndexRouteImport } from './routes/_authed/dashboard.projects.$code.index'
import { Route as AuthedDashboardProjectsCodeCCampaignCodeRouteImport } from './routes/_authed/dashboard.projects.$code.c.$campaignCode'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedCampaignsIndexRoute = AuthedCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCampaignsCodeApplyRoute =
  AuthedCampaignsCodeApplyRouteImport.update({
    id: '/campaigns/$code/apply',
    path: '/campaigns/$code/apply',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardProjectsCodeIndexRoute =
  AuthedDashboardProjectsCodeIndexRouteImport.update({
    id: '/projects/$code/',
    path: '/projects/$code/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardProjectsCodeCCampaignCodeRoute =
  AuthedDashboardProjectsCodeCCampaignCodeRouteImport.update({
    id: '/projects/$code/c/$campaignCode',
    path: '/projects/$code/c/$campaignCode',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/campaigns/': typeof AuthedCampaignsIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/campaigns/$code/apply': typeof AuthedCampaignsCodeApplyRoute
  '/dashboard/projects/$code/': typeof AuthedDashboardProjectsCodeIndexRoute
  '/dashboard/projects/$code/c/$campaignCode': typeof AuthedDashboardProjectsCodeCCampaignCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/campaigns': typeof AuthedCampaignsIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/campaigns/$code/apply': typeof AuthedCampaignsCodeApplyRoute
  '/dashboard/projects/$code': typeof AuthedDashboardProjectsCodeIndexRoute
  '/dashboard/projects/$code/c/$campaignCode': typeof AuthedDashboardProjectsCodeCCampaignCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authed/campaigns/': typeof AuthedCampaignsIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/campaigns/$code/apply': typeof AuthedCampaignsCodeApplyRoute
  '/_authed/dashboard/projects/$code/': typeof AuthedDashboardProjectsCodeIndexRoute
  '/_authed/dashboard/projects/$code/c/$campaignCode': typeof AuthedDashboardProjectsCodeCCampaignCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/campaigns/'
    | '/dashboard/'
    | '/campaigns/$code/apply'
    | '/dashboard/projects/$code/'
    | '/dashboard/projects/$code/c/$campaignCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/campaigns'
    | '/dashboard'
    | '/campaigns/$code/apply'
    | '/dashboard/projects/$code'
    | '/dashboard/projects/$code/c/$campaignCode'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/dashboard'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authed/campaigns/'
    | '/_authed/dashboard/'
    | '/_authed/campaigns/$code/apply'
    | '/_authed/dashboard/projects/$code/'
    | '/_authed/dashboard/projects/$code/c/$campaignCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/campaigns/': {
      id: '/_authed/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthedCampaignsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/campaigns/$code/apply': {
      id: '/_authed/campaigns/$code/apply'
      path: '/campaigns/$code/apply'
      fullPath: '/campaigns/$code/apply'
      preLoaderRoute: typeof AuthedCampaignsCodeApplyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/projects/$code/': {
      id: '/_authed/dashboard/projects/$code/'
      path: '/projects/$code'
      fullPath: '/dashboard/projects/$code/'
      preLoaderRoute: typeof AuthedDashboardProjectsCodeIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/projects/$code/c/$campaignCode': {
      id: '/_authed/dashboard/projects/$code/c/$campaignCode'
      path: '/projects/$code/c/$campaignCode'
      fullPath: '/dashboard/projects/$code/c/$campaignCode'
      preLoaderRoute: typeof AuthedDashboardProjectsCodeCCampaignCodeRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardProjectsCodeIndexRoute: typeof AuthedDashboardProjectsCodeIndexRoute
  AuthedDashboardProjectsCodeCCampaignCodeRoute: typeof AuthedDashboardProjectsCodeCCampaignCodeRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardProjectsCodeIndexRoute: AuthedDashboardProjectsCodeIndexRoute,
  AuthedDashboardProjectsCodeCCampaignCodeRoute:
    AuthedDashboardProjectsCodeCCampaignCodeRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
  AuthedCampaignsIndexRoute: typeof AuthedCampaignsIndexRoute
  AuthedCampaignsCodeApplyRoute: typeof AuthedCampaignsCodeApplyRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
  AuthedCampaignsIndexRoute: AuthedCampaignsIndexRoute,
  AuthedCampaignsCodeApplyRoute: AuthedCampaignsCodeApplyRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
